# Generated by Django 6.0 on 2025-12-15 11:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('father_myopia', models.BooleanField(default=False)),
                ('mother_myopia', models.BooleanField(default=False)),
                ('number_of_siblings', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of siblings')),
                ('birth_order', models.CharField(blank=True, choices=[('First', 'First-born'), ('Middle', 'Middle-born'), ('Last', 'Last-born'), ('Only', 'Only child')], max_length=10, null=True, verbose_name='Birth order')),
                ('sibling_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Section A: Student Demographics',
            },
        ),
        migrations.CreateModel(
            name='LifestyleBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outdoor_time_start', models.TimeField(blank=True, null=True)),
                ('outdoor_duration', models.CharField(choices=[('<1 hr', '<1 hr'), ('1-2 hrs', '1-2 hrs'), ('2-4 hrs', '2-4 hrs'), ('>4 hrs', '>4 hrs')], max_length=20)),
                ('sun_exposure', models.CharField(choices=[('<15 min', '<15 min'), ('15-30 min', '15-30 min'), ('30-60 min', '30-60 min'), ('>1 hr', '>1 hr')], max_length=20)),
                ('near_work_hours', models.CharField(choices=[('<2 hrs', '<2 hrs'), ('2-4 hrs', '2-4 hrs'), ('4-6 hrs', '4-6 hrs'), ('>6 hrs', '>6 hrs')], max_length=20)),
                ('screen_time', models.CharField(choices=[('<1 hr', '<1 hr'), ('1-3 hrs', '1-3 hrs'), ('3-5 hrs', '3-5 hrs'), ('>5 hrs', '>5 hrs')], max_length=20)),
                ('primary_device', models.CharField(choices=[('TV', 'TV'), ('Tablet', 'Tablet'), ('Mobile', 'Mobile'), ('Laptop', 'Laptop/Desktop')], max_length=20)),
                ('reading_distance', models.CharField(choices=[('<20 cm', '<20 cm'), ('20-30 cm', '20-30 cm'), ('>30 cm', '>30 cm')], max_length=20)),
                ('viewing_posture_ratio', models.CharField(choices=[('Low', 'Low'), ('High', 'High'), ('Optimum', 'Optimum')], max_length=10)),
                ('dietary_habit', models.CharField(choices=[('Balanced', 'Balanced'), ('Junk', 'Junk food-dominant'), ('Vegetarian', 'Vegetarian'), ('NonVegetarian', 'Non-vegetarian'), ('Other', 'Other')], max_length=20)),
                ('dietary_other', models.CharField(blank=True, max_length=100)),
                ('sleep_duration', models.CharField(choices=[('<6 hrs', '<6 hrs'), ('6-7 hrs', '6-7 hrs'), ('7-8 hrs', '7-8 hrs'), ('>8 hrs', '>8 hrs')], max_length=20)),
                ('usual_bedtime', models.CharField(choices=[('Before9', 'Before 9 PM'), ('9-10', '9-10 PM'), ('10-11', '10-11 PM'), ('After11', 'After 11 PM')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='Myopia_Study.student')),
            ],
            options={
                'verbose_name': 'Section B: Lifestyle',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school_type', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=20)),
                ('classroom_strength', models.CharField(choices=[('Small', '< 30'), ('Moderate', '30-50'), ('High', '> 50')], max_length=20)),
                ('seating_position', models.CharField(choices=[('Front', 'Front'), ('Middle', 'Middle'), ('Back', 'Back')], max_length=20)),
                ('lighting', models.CharField(choices=[('Dim', 'Dim'), ('Adequate', 'Adequate'), ('Bright', 'Bright')], max_length=20)),
                ('sunlight_source', models.CharField(choices=[('Natural', 'Natural'), ('Artificial', 'Artificial'), ('Both', 'Both')], max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='Myopia_Study.student')),
            ],
            options={
                'verbose_name': 'Section C: Environment',
            },
        ),
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('history_prior_diagnosis', models.BooleanField(default=False)),
                ('age_at_diagnosis', models.IntegerField(blank=True, null=True)),
                ('spectacle_change_3yrs', models.BooleanField(default=False)),
                ('compliance', models.CharField(choices=[('Always', 'Always'), ('Sometimes', 'Sometimes'), ('Rarely', 'Rarely')], max_length=20)),
                ('current_re', models.CharField(blank=True, max_length=10)),
                ('current_le', models.CharField(blank=True, max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='Myopia_Study.student')),
            ],
            options={
                'verbose_name': 'Section D: History',
            },
        ),
        migrations.CreateModel(
            name='ClinicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now, help_text='Date of clinical examination')),
                ('unaided_va_re', models.CharField(blank=True, max_length=20, verbose_name='Unaided Visual Acuity (Right Eye)')),
                ('unaided_va_le', models.CharField(blank=True, max_length=20, verbose_name='Unaided Visual Acuity (Left Eye)')),
                ('aided_va_re', models.CharField(blank=True, max_length=20, verbose_name='Aided Visual Acuity (Right Eye)')),
                ('aided_va_le', models.CharField(blank=True, max_length=20, verbose_name='Aided Visual Acuity (Left Eye)')),
                ('spherical_re', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cylindrical_re', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis_re', models.PositiveIntegerField(blank=True, null=True)),
                ('spherical_le', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cylindrical_le', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis_le', models.PositiveIntegerField(blank=True, null=True)),
                ('axial_length_re', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Axial Length Right Eye (mm)')),
                ('axial_length_le', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Axial Length Left Eye (mm)')),
                ('progression_noted', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_examinations', to='Myopia_Study.student')),
            ],
            options={
                'verbose_name': 'Section F: Clinical Examination',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='AwarenessSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aware_symptoms', models.BooleanField(default=False)),
                ('follows_measures', models.CharField(choices=[('Always', 'Always'), ('Sometimes', 'Sometimes'), ('Never', 'Never')], max_length=20)),
                ('source_of_awareness', models.CharField(blank=True, max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='Myopia_Study.student')),
            ],
            options={
                'verbose_name': 'Section E: Awareness',
            },
        ),
    ]
