# Generated by Django 6.0 on 2025-12-31 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('BASELINE', 'Baseline'), ('FOLLOW_UP', 'Follow-up')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('parental_myopia', models.CharField(blank=True, max_length=20, null=True)),
                ('num_siblings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('birth_order', models.CharField(blank=True, max_length=20, null=True)),
                ('siblings_myopia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosed_earlier', models.BooleanField(default=False)),
                ('age_at_diagnosis', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power_changed_last_3yrs', models.BooleanField(default=False)),
                ('compliance', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_re', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_le', models.CharField(blank=True, max_length=20, null=True)),
                ('current_re', models.CharField(blank=True, max_length=20, null=True)),
                ('current_le', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myopia_Study.clinicalvisit')),
            ],
        ),
        migrations.CreateModel(
            name='AwarenessSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aware_eye_strain', models.BooleanField(default=False)),
                ('access_to_vision_care', models.BooleanField(default=False)),
                ('follows_preventive_measures', models.CharField(blank=True, max_length=20, null=True)),
                ('source_of_awareness', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myopia_Study.clinicalvisit')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(blank=True, max_length=20, null=True)),
                ('classroom_strength', models.CharField(blank=True, max_length=20, null=True)),
                ('seating_position', models.CharField(blank=True, max_length=20, null=True)),
                ('teaching_methodology', models.CharField(blank=True, max_length=30, null=True)),
                ('lighting', models.CharField(blank=True, max_length=20, null=True)),
                ('sunlight_source', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myopia_Study.clinicalvisit')),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outdoor_time', models.TimeField(blank=True, null=True)),
                ('outdoor_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('sun_exposure', models.CharField(blank=True, max_length=20, null=True)),
                ('near_work_hours', models.CharField(blank=True, max_length=20, null=True)),
                ('screen_time', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_device', models.CharField(blank=True, max_length=20, null=True)),
                ('reading_distance', models.CharField(blank=True, max_length=20, null=True)),
                ('viewing_posture_ratio', models.CharField(blank=True, max_length=20, null=True)),
                ('dietary_habit', models.CharField(blank=True, max_length=20, null=True)),
                ('dietary_other', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_duration', models.CharField(blank=True, max_length=20, null=True)),
                ('usual_bedtime', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myopia_Study.clinicalvisit')),
            ],
        ),
        migrations.CreateModel(
            name='OcularExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncorrectedvisual_acuity_right_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('uncorrectedvisual_acuity_left_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('bestcorrectedvisual_acuity_right_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('bestcorrectedvisual_acuity_left_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('cycloplegic_auto_refraction_right_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('cycloplegic_auto_refraction_left_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('spherical_power_right_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('spherical_power_left_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('axial_length_right_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('axial_length_left_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('corneal_curvature_right_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('corneal_curvature_left_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('central_corneal_thickness_right_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('central_corneal_thickness_left_eye', models.CharField(blank=True, max_length=20, null=True)),
                ('anterior_segment_finding_right_eye', models.TextField(blank=True, null=True)),
                ('anterior_segment_finding_left_eye', models.TextField(blank=True, null=True)),
                ('amblyopia_or_strabismus', models.BooleanField(default=False)),
                ('fundus_examination_finding_righ_eye', models.TextField(blank=True, null=True)),
                ('fundus_examination_finding_left_eye', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myopia_Study.clinicalvisit')),
            ],
        ),
        migrations.AddField(
            model_name='clinicalvisit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myopia_Study.student'),
        ),
    ]
