# Generated by Django 6.0 on 2026-01-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('locked', 'Locked'), ('flagged', 'Flagged'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
