# Generated by Django 6.0 on 2025-12-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalfactor',
            name='classroom_strength',
            field=models.CharField(choices=[('Small', '<30'), ('Moderate', '30–50'), ('High', '>50')], max_length=20),
        ),
    ]
