# Generated by Django 6.0 on 2025-12-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0002_alter_environmentalfactor_classroom_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalfactor',
            name='teaching_methodology',
            field=models.CharField(choices=[('Digital', 'Digital (projectors/screens)'), ('Traditional', 'Traditional (blackboard/books)')], default='Traditional', max_length=20),
            preserve_default=False,
        ),
    ]
