# Generated by Django 6.0 on 2025-12-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0003_environmentalfactor_teaching_methodology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalhistory',
            options={'verbose_name': 'Section D: Clinical History'},
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='history_prior_diagnosis',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='spectacle_change_3yrs',
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='diagnosed_earlier',
            field=models.BooleanField(default='False', verbose_name='Diagnosed with myopia earlier?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='power_changed_last_3yrs',
            field=models.BooleanField(default='False', verbose_name='Spectacle power changed in last 3 years?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='previous_le',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='previous_re',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='age_at_diagnosis',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age at diagnosis (years)'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='current_le',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='current_re',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
