# Generated by Django 6.0 on 2025-12-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0004_alter_clinicalhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awarenesssafety',
            options={'verbose_name': 'Section E: Awareness & Safety'},
        ),
        migrations.RenameField(
            model_name='awarenesssafety',
            old_name='follows_measures',
            new_name='follows_preventive_measures',
        ),
        migrations.RemoveField(
            model_name='awarenesssafety',
            name='aware_symptoms',
        ),
        migrations.AddField(
            model_name='awarenesssafety',
            name='aware_eye_strain',
            field=models.BooleanField(default='False', verbose_name='Aware of eye strain symptoms?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='awarenesssafety',
            name='source_of_awareness',
            field=models.CharField(blank=True, help_text='Comma-separated: School, Family, Doctor, Media, Other', max_length=200),
        ),
    ]
