# Generated by Django 6.0 on 2025-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0005_alter_awarenesssafety_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenesssafety',
            name='access_to_vision_care',
            field=models.BooleanField(default='False', verbose_name='Access to vision care in your area?'),
            preserve_default=False,
        ),
    ]
