# Generated by Django 6.0 on 2025-12-16 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0006_awarenesssafety_access_to_vision_care'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcularExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ucva_re', models.CharField(blank=True, max_length=20)),
                ('ucva_le', models.CharField(blank=True, max_length=20)),
                ('bcva_re', models.CharField(blank=True, max_length=20)),
                ('bcva_le', models.CharField(blank=True, max_length=20)),
                ('cyclo_se_re', models.CharField(blank=True, max_length=20)),
                ('cyclo_se_le', models.CharField(blank=True, max_length=20)),
                ('spherical_re', models.CharField(blank=True, max_length=20)),
                ('spherical_le', models.CharField(blank=True, max_length=20)),
                ('axial_length_re', models.CharField(blank=True, max_length=20)),
                ('axial_length_le', models.CharField(blank=True, max_length=20)),
                ('keratometry_re', models.CharField(blank=True, max_length=50)),
                ('keratometry_le', models.CharField(blank=True, max_length=50)),
                ('cct_re', models.CharField(blank=True, max_length=20)),
                ('cct_le', models.CharField(blank=True, max_length=20)),
                ('anterior_segment_re', models.TextField(blank=True)),
                ('anterior_segment_le', models.TextField(blank=True)),
                ('amblyopia_or_strabismus', models.BooleanField()),
                ('fundus_re', models.TextField(blank=True)),
                ('fundus_le', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='Myopia_Study.student')),
            ],
            options={
                'verbose_name': 'Section F: Ocular Examination',
            },
        ),
    ]
