# Generated by Django 6.0 on 2025-12-17 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0007_ocularexamination'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit_date', models.DateField()),
                ('next_visit_date', models.DateField()),
                ('status', models.CharField(choices=[('Due', 'Due'), ('Overdue', 'Overdue'), ('Completed', 'Completed')], default='Due', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='Myopia_Study.student')),
            ],
            options={
                'ordering': ['next_visit_date'],
            },
        ),
    ]
