# Generated by Django 6.0 on 2025-12-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0008_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='awarenesssafety',
            name='visit_type',
            field=models.CharField(choices=[('BASELINE', 'Baseline'), ('FOLLOW_UP', 'Follow-up')], default='BASELINE', max_length=10),
        ),
        migrations.AddField(
            model_name='clinicalhistory',
            name='visit_type',
            field=models.CharField(choices=[('BASELINE', 'Baseline'), ('FOLLOW_UP', 'Follow-up')], default='BASELINE', max_length=10),
        ),
        migrations.AddField(
            model_name='environmentalfactor',
            name='visit_type',
            field=models.CharField(choices=[('BASELINE', 'Baseline'), ('FOLLOW_UP', 'Follow-up')], default='BASELINE', max_length=10),
        ),
        migrations.AddField(
            model_name='lifestylebehavior',
            name='visit_type',
            field=models.CharField(choices=[('BASELINE', 'Baseline'), ('FOLLOW_UP', 'Follow-up')], default='BASELINE', max_length=10),
        ),
        migrations.AddField(
            model_name='ocularexamination',
            name='visit_type',
            field=models.CharField(choices=[('BASELINE', 'Baseline'), ('FOLLOW_UP', 'Follow-up')], default='BASELINE', max_length=10),
        ),
    ]
