# Generated by Django 6.0 on 2025-12-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myopia_Study', '0009_awarenesssafety_visit_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awarenesssafety',
            name='visit_type',
        ),
        migrations.RemoveField(
            model_name='clinicalhistory',
            name='visit_type',
        ),
        migrations.RemoveField(
            model_name='environmentalfactor',
            name='visit_type',
        ),
        migrations.RemoveField(
            model_name='lifestylebehavior',
            name='visit_type',
        ),
        migrations.RemoveField(
            model_name='ocularexamination',
            name='visit_type',
        ),
        migrations.AddField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
